# Generated by Django 4.2.1 on 2023-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="example_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="conf_files/",
                verbose_name="Example File",
            ),
        ),
    ]
