# Generated by Django 4.2.1 on 2023-08-15 04:52

import apps.business_app.models.uploaded_files
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_systemuser_phone"),
        ("business_app", "0002_siteconfiguration_example_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(max_length=150, verbose_name="custom name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to=apps.business_app.models.uploaded_files.user_directory_path,
                        validators=[
                            apps.business_app.models.uploaded_files.FileExtensionValidator()
                        ],
                        verbose_name="Original File",
                    ),
                ),
                (
                    "system_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.systemuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
            },
        ),
    ]
