# Generated by Django 4.2.1 on 2023-08-15 06:12

import apps.business_app.models.uploaded_files
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0003_uploadedfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="processed_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.business_app.models.uploaded_files.user_directory_path,
                verbose_name="Processed File",
            ),
        ),
    ]
