# Generated by Django 4.2.1 on 2023-08-16 04:50

import apps.business_app.models.uploaded_files
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_systemuser_phone"),
        ("business_app", "0004_uploadedfiles_processed_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfiles",
            name="processed_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.business_app.models.uploaded_files.user_processed_directory_path,
                verbose_name="Processed File",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfiles",
            name="system_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="users_app.systemuser",
            ),
        ),
    ]
