# Generated by Django 4.2.1 on 2023-09-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0006_add_default_allowed_filetypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlleleNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Number")),
                ("element", models.CharField(max_length=3, verbose_name="Element")),
                (
                    "custom_element_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Custom Element Name",
                    ),
                ),
                ("symbol", models.CharField(max_length=150, verbose_name="Symbol")),
                ("x_coordinate", models.FloatField(verbose_name="X Coordinate")),
                ("y_coordinate", models.FloatField(verbose_name="Y Coordinate")),
                ("z_coordinate", models.FloatField(verbose_name="Z Coordinate")),
                ("rs", models.CharField(max_length=150, verbose_name="RS")),
                (
                    "parents",
                    models.ManyToManyField(blank=True, to="business_app.allelenode"),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele_nodes",
                        to="business_app.uploadedfiles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele Node",
                "verbose_name_plural": "Allele Nodes",
            },
        ),
    ]
