# Generated by Django 4.2.1 on 2023-10-17 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0009_allelenode_unique_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allelenode",
            old_name="parents",
            new_name="children",
        ),
    ]
