# Generated by Django 4.2.1 on 2023-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0010_rename_parents_allelenode_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="children_qty",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Children Quantity"
            ),
        ),
    ]
