# Generated by Django 4.2.1 on 2023-10-27 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0011_allelenode_children_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allelenode",
            name="children_qty",
        ),
    ]
