# Generated by Django 4.2.1 on 2024-02-03 04:48

from django.db import migrations


def remove_empty_alleles(apps, schema_editor):
    AlleleNode = apps.get_model("business_app", "AlleleNode")
    AlleleNode.objects.filter(uploaded_file__isnull=True).delete()
    print()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0012_remove_allelenode_children_qty"),
    ]

    operations = [
        migrations.RunPython(remove_empty_alleles, migrations.RunPython.noop),
    ]
