# Generated by Django 4.2.1 on 2024-02-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0013_remove_empty_alleles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allelenode",
            name="uploaded_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allele_nodes",
                to="business_app.uploadedfiles",
            ),
            preserve_default=False,
        ),
    ]
