# Generated by Django 4.2.1 on 2024-02-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0017_remove_uploadedfiles_processed_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allelenode",
            name="x_coordinate",
        ),
        migrations.RemoveField(
            model_name="allelenode",
            name="y_coordinate",
        ),
        migrations.RemoveField(
            model_name="allelenode",
            name="z_coordinate",
        ),
        migrations.AlterField(
            model_name="pdbfiles",
            name="original_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdb_files",
                to="business_app.uploadedfiles",
                verbose_name="Original File",
            ),
        ),
    ]
