# Generated by Django 4.2.1 on 2024-02-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0018_remove_allelenode_x_coordinate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Region"
            ),
        ),
    ]
