# Generated by Django 4.2.1 on 2024-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0020_initialfiledata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdbfiles",
            options={"verbose_name": "PDB File", "verbose_name_plural": "PDB Files"},
        ),
        migrations.AddField(
            model_name="initialfiledata",
            name="row_index",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Row Index"),
            preserve_default=False,
        ),
    ]
