# Generated by Django 4.2.1 on 2024-05-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_systemuser_phone"),
        ("business_app", "0022_customgeneratedpdbfiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgeneratedpdbfiles",
            name="system_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_generated_pdb_files",
                to="users_app.systemuser",
            ),
        ),
    ]
