# Generated by Django 4.2.1 on 2024-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0023_alter_customgeneratedpdbfiles_system_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="google_sheet_id",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
