# Generated by Django 4.2.1 on 2024-05-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0024_uploadedfiles_google_sheet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgeneratedpdbfiles",
            name="file",
            field=models.FileField(
                upload_to="generated_pdb/", verbose_name="Processed File"
            ),
        ),
    ]
