# Generated by Django 5.0.6 on 2024-06-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0024_uploadedfiles_google_sheet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgeneratedpdbfiles",
            name="file",
            field=models.FileField(
                upload_to="generated_pdb/", verbose_name="Processed File"
            ),
        ),
        migrations.CreateModel(
            name="InitialXyzExpansionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_value", models.FloatField(verbose_name="X original value")),
                ("y_value", models.FloatField(verbose_name="Y original value")),
                ("z_value", models.FloatField(verbose_name="Z original value")),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_xyz_expansion_info",
                        to="business_app.uploadedfiles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initial XYZ expansion Data",
                "verbose_name_plural": "Initial XYZ expansion Data",
            },
        ),
    ]
