# Generated by Django 4.2.1 on 2024-06-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0025_alter_customgeneratedpdbfiles_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(max_length=255, verbose_name="Event Name"),
                ),
                (
                    "event_icon",
                    models.ImageField(upload_to="images/", verbose_name="Event Icon"),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.CharField(max_length=255, verbose_name="Latitude")),
                (
                    "longitude",
                    models.CharField(max_length=255, verbose_name="Longitude"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.event",
                        verbose_name="Event Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marker",
                "verbose_name_plural": "Markers",
            },
        ),
    ]
