# Generated by Django 5.0.6 on 2024-07-11 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0025_alter_customgeneratedpdbfiles_file_and_more"),
        ("business_app", "0026_event_marker"),
    ]

    operations = []
