# Generated by Django 5.0.6 on 2024-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0027_merge_20240711_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="end_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("After Christ (AC)", "Afterchrist"),
                    ("Before Christ (BC)", "Beforechrist"),
                    ("Before Present (YBP)", "Beforepresent"),
                ],
                max_length=255,
                null=True,
                verbose_name="End Date Format",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="start_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("After Christ (AC)", "Afterchrist"),
                    ("Before Christ (BC)", "Beforechrist"),
                    ("Before Present (YBP)", "Beforepresent"),
                ],
                max_length=255,
                null=True,
                verbose_name="Start Date Format",
            ),
        ),
        migrations.AlterField(
            model_name="marker",
            name="end_date",
            field=models.IntegerField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="marker",
            name="start_date",
            field=models.IntegerField(verbose_name="Start Date"),
        ),
    ]
