# Generated by Django 4.2.7 on 2024-07-22 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_systemuser_phone"),
        ("business_app", "0028_marker_end_format_marker_start_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="WorkingCopyOfOriginalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "google_sheet_id_copy",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "pdb_file_copy",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "system_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.systemuser",
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.uploadedfiles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded File",
                "verbose_name_plural": "Uploaded Files",
            },
        ),
    ]
