# Generated by Django 4.2.7 on 2024-07-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0030_alter_workingcopyoforiginalfile_pdb_file_copy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingcopyoforiginalfile",
            name="google_sheet_id_copy",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="workingcopyoforiginalfile",
            name="pdb_file_copy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.customgeneratedpdbfiles",
                unique=True,
            ),
        ),
    ]
