# Generated by Django 4.2.7 on 2024-07-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_app",
            "0031_alter_workingcopyoforiginalfile_google_sheet_id_copy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingcopyoforiginalfile",
            name="pdb_file_copy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.customgeneratedpdbfiles",
            ),
        ),
    ]
