# Generated by Django 4.2.1 on 2024-08-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0033_alter_workingcopyoforiginalfile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Name of the Layers"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
            ],
            options={
                "verbose_name": "Layer",
                "verbose_name_plural": "Layers",
            },
        ),
    ]
