# Generated by Django 5.0.6 on 2024-09-13 15:48

import apps.business_app.models.pdb_files
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0034_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdbfiles",
            name="file",
            field=models.FileField(
                null=True,
                upload_to=apps.business_app.models.pdb_files.user_processed_directory_path,
                verbose_name="Processed File",
            ),
        ),
    ]
