# Generated by Django 5.0.6 on 2024-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0035_alter_pdbfiles_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdbfiles",
            name="pdb_content",
            field=models.TextField(null=True, verbose_name="Processed File Content"),
        ),
    ]
