# Generated by Django 5.0.6 on 2024-09-13 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0036_pdbfiles_pdb_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdbfiles",
            name="file",
        ),
    ]
