# Generated by Django 5.0.6 on 2024-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0037_remove_pdbfiles_file"),
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdbfiles",
            name="kind",
            field=models.CharField(
                choices=[("G", "Grahp generated"), ("D", "Excel generated")],
                default="D",
                max_length=1,
                verbose_name="Kind",
            ),
        ),
    ]
