# Generated by Django 5.0.6 on 2024-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0038_pdbfiles_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="nx_graph_dim",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="Nx Graph Dimension"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nx_graph_k",
            field=models.FloatField(default=0.15, verbose_name="Nx Graph K constant"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nx_graph_training_iterations",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Nx Graph Training iterations"
            ),
        ),
    ]
