# Generated by Django 5.0.6 on 2024-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0039_siteconfiguration_nx_graph_dim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="nx_graph_scale",
            field=models.PositiveSmallIntegerField(
                default=500, verbose_name="Nx Graph Scale"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="nx_graph_k",
            field=models.FloatField(default=0.5, verbose_name="Nx Graph K constant"),
        ),
    ]
