# Generated by Django 4.2.16 on 2024-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0040_siteconfiguration_nx_graph_scale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        default="Feature", max_length=255, verbose_name="FeatureType"
                    ),
                ),
                ("feature_id", models.IntegerField(verbose_name="ID")),
                (
                    "mag",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mag"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Place"
                    ),
                ),
                (
                    "time",
                    models.IntegerField(blank=True, null=True, verbose_name="Time"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "timefinal",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="TimeFinal"
                    ),
                ),
                (
                    "geometry_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GeometryType",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(blank=True, null=True, verbose_name="Coordinates"),
                ),
            ],
        ),
    ]
