# Generated by Django 5.0.6 on 2024-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0041_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="timeline_appearence",
            field=models.IntegerField(
                null=True, verbose_name="Appearance on the timeline"
            ),
        ),
    ]
