# Generated by Django 5.0.6 on 2024-10-09 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0041_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="nx_graph_dim",
        ),
    ]
