# Generated by Django 5.0.6 on 2024-10-13 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0042_allelenode_timeline_appearence"),
        ("business_app", "0042_remove_siteconfiguration_nx_graph_dim"),
    ]

    operations = []
