# Generated by Django 4.2.16 on 2024-10-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0042_remove_siteconfiguration_nx_graph_dim"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="reference",
            field=models.TextField(blank=True, null=True, verbose_name="Reference"),
        ),
    ]
