# Generated by Django 5.0.6 on 2024-10-31 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0043_marker_reference"),
        ("business_app", "0043_merge_20241023_1652"),
    ]

    operations = []
