# Generated by Django 4.2.16 on 2024-11-12 00:17
import json
from django.db import migrations
from termcolor import colored


def load_data_from_timelinejson(apps, schema_editor):
    """Carga datos desde el archivo JSON."""
    Feature = apps.get_model("business_app", "Feature")
    with open(
        "apps/business_app/fixtures/migration-timeline.json", "r", encoding="utf-8"
    ) as file:
        data = json.load(file)
        # Verificar si hay features para procesar
        if not data:
            print()
            print(
                colored(
                    "There are no features to load.",
                    "red",
                    attrs=["reverse", "blink"],
                )
            )
            return
        # Iterar sobre las features y guardarlas en la base de datos
        counter = 0
        for feature in data:
            counter += 1
            properties = feature["properties"]
            geometry = feature["geometry"]
            Feature.objects.create(
                feature_type=feature["type"],
                feature_id=properties["id"],
                mag=properties.get("mag"),
                place=properties.get("place"),
                time=properties["time"],
                title=properties.get("title"),
                timefinal=properties["timefinal"],
                geometry_type=geometry["type"],
                coordinates=geometry["coordinates"],
            )
        print()
        print(
            colored(
                f"Successfully added {counter} features to the system",
                "green",
                attrs=["reverse", "blink"],
            )
        )


def delete_feature_data(apps, schema_editor):
    """Elimina todos los datos de features."""
    Feature = apps.get_model("business_app", "Feature")
    Feature.objects.all().delete()
    print()
    print(
        colored(
            "Cleaned Feature table.",
            "red",
            attrs=["reverse", "blink"],
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0044_merge_0043_marker_reference_0043_merge_20241023_1652"),
    ]

    operations = [
        migrations.RunPython(load_data_from_timelinejson, delete_feature_data),
    ]
