# Generated by Django 5.0.6 on 2024-12-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0045_fill_feature_data"),
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.CreateModel(
            name="RegionCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country by region",
                "verbose_name_plural": "Countries by region",
            },
        ),
        migrations.AddField(
            model_name="region",
            name="countries",
            field=models.ManyToManyField(
                through="business_app.RegionCountry", to="users_app.country"
            ),
        ),
    ]
