# Generated by Django 5.0.6 on 2025-01-01 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0046_alter_marker_description"),
        ("business_app", "0047_fill_regions_by_country"),
    ]

    operations = []
