# Generated by Django 4.2.16 on 2025-01-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0014_merge_20240905_0947"),
        ("business_app", "0048_merge_20250101_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pause_time",
            field=models.IntegerField(
                default=6000, verbose_name="Pause Time in Milliseconds"
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="pause_time",
            field=models.IntegerField(
                default=0, verbose_name="Pause Time in Milliseconds"
            ),
        ),
        migrations.AlterField(
            model_name="regioncountry",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="region_country",
                to="users_app.country",
            ),
        ),
    ]
