# Generated by Django 5.0.6 on 2025-01-15 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0050_alter_allelenode_rs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allelenode",
            name="symbol",
        ),
    ]
