# Generated by Django 5.0.6 on 2025-01-16 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0049_event_pause_time_marker_pause_time_and_more"),
        ("business_app", "0051_remove_allelenode_symbol"),
    ]

    operations = []
