# Generated by Django 5.0.6 on 2025-01-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0052_merge_20250115_2112"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="sphere_radius_factor",
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="stick_radius_factor",
            field=models.FloatField(default=0.003),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="stick_radius_if_children",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="stick_radius_min_value",
            field=models.FloatField(default=0.2),
        ),
    ]
