# Generated by Django 5.0.6 on 2025-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0053_siteconfiguration_sphere_radius_factor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="sphere_radius",
            field=models.FloatField(null=True, verbose_name="Sphere Radius"),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="stick_radius",
            field=models.FloatField(null=True, verbose_name="Stick Radius"),
        ),
    ]
