# Generated by Django 5.0.6 on 2025-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0054_allelenode_sphere_radius_allelenode_stick_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allelenode",
            name="sphere_radius",
            field=models.FloatField(
                default=2.4000000000000004, verbose_name="Sphere Radius"
            ),
        ),
        migrations.AlterField(
            model_name="allelenode",
            name="stick_radius",
            field=models.FloatField(default=0.2, verbose_name="Stick Radius"),
        ),
    ]
