# Generated by Django 4.2.16 on 2025-01-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0054_allelenode_sphere_radius_allelenode_stick_radius"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkerGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Image name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Image"),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.marker",
                        verbose_name="Marker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marker Gallery",
                "verbose_name_plural": "Markers Gallery",
            },
        ),
    ]
