# Generated by Django 4.2.16 on 2025-02-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0055_markergallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markergallery",
            name="marker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marker_galleries",
                to="business_app.marker",
                verbose_name="Marker",
            ),
        ),
    ]
