# Generated by Django 5.0.6 on 2025-02-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0056_alter_markergallery_marker"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Event Name")),
                (
                    "icon",
                    models.ImageField(upload_to="images/", verbose_name="Event Icon"),
                ),
                (
                    "pause_time",
                    models.IntegerField(
                        default=6000, verbose_name="Pause Time in Milliseconds"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event type",
                "verbose_name_plural": "Event types",
            },
        ),
    ]
