# Generated by Django 5.0.6 on 2025-02-22 05:16

from django.db import migrations


def migrate_info(apps, schema_editor):
    Marker = apps.get_model("business_app", "Marker")
    Event = apps.get_model("business_app", "Event")
    EventType = apps.get_model("business_app", "EventType")

    events = Event.objects.all().iterator()
    to_delete = []

    for event in events:
        event_type = EventType.objects.create(
            name=event.event_name,
            icon=event.event_icon,
            pause_time=event.pause_time,
        )
        event.event_type = event_type
        event.save(update_fields=["event_type"])
        markers = Marker.objects.filter(event_type=event)
        for marker in markers:
            event = Event.objects.create(
                event_name="Fill later",
                description=marker.description,
                event_type=event_type,
                start_date=marker.start_date,
                end_date=marker.end_date,
            )
            marker.event_type = event
            marker.save(update_fields=["event_type"])
        to_delete.append(event.id)
    Event.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_app",
            "0058_event_description_event_end_date_event_event_type_and_more",
        ),
    ]
    operations = [
        migrations.RunPython(migrate_info, migrations.RunPython.noop),
    ]
