# Generated by Django 5.0.6 on 2025-02-22 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0059_auto_20250222_0516"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marker",
            old_name="event_type",
            new_name="event",
        ),
        migrations.RemoveField(
            model_name="marker",
            name="description",
        ),
        migrations.RemoveField(
            model_name="marker",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="marker",
            name="end_format",
        ),
        migrations.RemoveField(
            model_name="marker",
            name="pause_time",
        ),
        migrations.RemoveField(
            model_name="marker",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="marker",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="marker",
            name="start_format",
        ),
    ]
