# Generated by Django 5.0.6 on 2025-02-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0060_rename_event_type_marker_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markers",
                to="business_app.event",
                verbose_name="Event",
            ),
        ),
        migrations.CreateModel(
            name="EventGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Image name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Image"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_galleries",
                        to="business_app.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Gallery",
                "verbose_name_plural": "Event Gallery",
            },
        ),
        migrations.DeleteModel(
            name="MarkerGallery",
        ),
    ]
