# Generated by Django 5.0.6 on 2025-02-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0061_alter_marker_event_eventgallery_delete_markergallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventgallery",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_gallery",
                to="business_app.event",
                verbose_name="Event",
            ),
        ),
    ]
