# Generated by Django 5.0.6 on 2025-05-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0062_alter_eventgallery_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="age_1",
            field=models.IntegerField(
                help_text="First value in the appereance range",
                null=True,
                verbose_name="Appearance on the timeline",
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="age_2",
            field=models.IntegerField(
                help_text="Last value in the appereance range",
                null=True,
                verbose_name="Disappearance on the timeline",
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_afr_amr",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Frequency African American/Afro-Caribbean",
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_afr_eas",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency East-African"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_afr_nor",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency North-African"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_afr_swe",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency South-West-African"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_amr",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency American"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_ca",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency Central-Asian"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_csa",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency Central/South-Asian"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_eas",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency East Asian"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_eur",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency European"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency Latino"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_nea",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency Near Eastern"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_oce",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency Oceanian"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_sa",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency South-Asian"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_ssa",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency Sub-Saharan African"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="increment",
            field=models.TextField(null=True, verbose_name="RS incremented"),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="loss",
            field=models.TextField(null=True, verbose_name="RS lost"),
        ),
    ]
