# Generated by Django 5.0.6 on 2025-04-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0062_alter_eventgallery_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="origin_1",
            field=models.IntegerField(
                help_text="First value in the appereance range",
                null=True,
                verbose_name="Origin 1",
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="origin_2",
            field=models.IntegerField(
                help_text="Last value in the appereance range",
                null=True,
                verbose_name="Appearance on the timeline",
            ),
        ),
    ]
