# Generated by Django 5.0.6 on 2025-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0063_allelenode_origin_1_allelenode_origin_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="increment",
            field=models.TextField(null=True, verbose_name="RS incremented"),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="loss",
            field=models.TextField(null=True, verbose_name="RS lost"),
        ),
    ]
