# Generated by Django 5.0.6 on 2025-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0063_allelenode_age_1_allelenode_age_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="Color"
            ),
        ),
    ]
