# Generated by Django 5.0.6 on 2025-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0064_allelenode_increment_allelenode_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="frec_afr",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency AFR"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_ame",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency AME"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_eas",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency EAS"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_eur",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency EUR"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="frec_sas",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Frequency SAS"
            ),
        ),
    ]
