# Generated by Django 5.0.6 on 2025-05-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0064_region_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="symbol",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
