# Generated by Django 5.0.6 on 2025-05-06 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0065_region_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regioncountry",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries_for_region",
                to="business_app.region",
            ),
        ),
    ]
