# Generated by Django 5.0.6 on 2025-05-06 16:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0066_alter_regioncountry_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="color",
            field=colorfield.fields.ColorField(
                default="#808080",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
