# Generated by Django 5.0.6 on 2025-06-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0067_alter_region_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="x_cartesian_coord",
            field=models.IntegerField(
                null=True, verbose_name="X cartesian coordinates"
            ),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="y_cartesian_coord",
            field=models.IntegerField(
                null=True, verbose_name="Y cartesian coordinates"
            ),
        ),
    ]
