# Generated by Django 5.0.6 on 2025-08-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0067_alter_region_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("C", "Completed"), ("I", "Not completed")],
                        default="I",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gene",
                "verbose_name_plural": "Genes",
            },
        ),
    ]
