# Generated by Django 5.0.6 on 2025-08-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0068_gene"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="gene",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="business_app.gene",
            ),
        ),
    ]
