# Generated by Django 5.0.6 on 2025-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0069_uploadedfiles_gene"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="predefined",
            field=models.BooleanField(default=False, verbose_name="predefined"),
        ),
    ]
