# Generated by Django 5.0.6 on 2025-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0070_uploadedfiles_predefined"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "genes",
                    models.ManyToManyField(
                        related_name="groups", to="business_app.gene"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gene Status",
                "verbose_name_plural": "Gene Statuses",
            },
        ),
    ]
