# Generated by Django 5.0.6 on 2025-09-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0070_uploadedfiles_predefined"),
    ]

    operations = [
        migrations.AddField(
            model_name="gene",
            name="formation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
