# Generated by Django 5.0.6 on 2025-09-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0071_genegroups"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "Percent"), ("B", "Boolean")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("requires_evidence", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Gene status",
                "verbose_name_plural": "Gene status",
            },
        ),
        migrations.AlterModelOptions(
            name="genegroups",
            options={
                "verbose_name": "Gene Group",
                "verbose_name_plural": "Gene Groups",
            },
        ),
        migrations.CreateModel(
            name="GeneStatusMiddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="gene_status_evidence/"
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.gene",
                    ),
                ),
                (
                    "gene_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.genestatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gene status Middle",
                "verbose_name_plural": "Gene status Middle",
            },
        ),
    ]
