# Generated by Django 5.0.6 on 2025-09-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0072_genestatus_alter_genegroups_options_genestatusmiddle"),
    ]

    operations = [
        migrations.AddField(
            model_name="genestatusmiddle",
            name="value",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="genestatusmiddle",
            name="gene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gene_status_list",
                to="business_app.gene",
            ),
        ),
        migrations.AlterField(
            model_name="genestatusmiddle",
            name="gene_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gene_list",
                to="business_app.genestatus",
            ),
        ),
    ]
