# Generated by Django 5.0.6 on 2025-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_app",
            "0073_genestatusmiddle_value_alter_genestatusmiddle_gene_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DeseaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DeseaseGroup",
                "verbose_name_plural": "DeseaseGroups",
            },
        ),
    ]
