# Generated by Django 5.0.6 on 2025-09-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_app",
            "0073_genestatusmiddle_value_alter_genestatusmiddle_gene_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Disease Group",
                "verbose_name_plural": "Disease Groups",
            },
        ),
        migrations.CreateModel(
            name="DiseaseSubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "disease_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.diseasegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease SubGroup",
                "verbose_name_plural": "Disease SubGroups",
            },
        ),
    ]
