# Generated by Django 5.0.6 on 2025-09-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0074_diseasegroup_diseasesubgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "disease_subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.diseasesubgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disorder",
                "verbose_name_plural": "Disorders",
            },
        ),
    ]
