# Generated by Django 5.0.6 on 2025-09-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0075_disorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="disorder",
            name="genes",
            field=models.ManyToManyField(
                related_name="disorders", to="business_app.gene"
            ),
        ),
    ]
