# Generated by Django 5.0.6 on 2025-09-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0076_disorder_genes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disorder",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
