# Generated by Django 5.0.6 on 2025-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0077_alter_disorder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene",
            name="status",
            field=models.SmallIntegerField(default=0),
        ),
    ]
