# Generated by Django 5.0.6 on 2025-10-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0078_alter_gene_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseasesubgroup",
            name="disease_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subgroups",
                to="business_app.diseasegroup",
            ),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="disease_subgroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disorders",
                to="business_app.diseasesubgroup",
            ),
        ),
    ]
