# Generated by Django 5.0.6 on 2025-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0079_alter_diseasesubgroup_disease_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genestatusmiddle",
            name="value",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
