# Generated by Django 5.0.6 on 2025-11-18 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0081_genestatus_created_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genestatusmiddle",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genestatusmiddle",
            name="updated_timestamp",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated timestamp"
            ),
        ),
    ]
