# Generated by Django 5.0.6 on 2025-11-26 19:31

from django.db import migrations


def update_gene_list(apps, schema_editor):
    Gene = apps.get_model("business_app", "Gene")
    GeneGroups = apps.get_model("business_app", "GeneGroups")

    dict_for_update = {
        1: [  # The key 1 corresponds to Pharmacodynamic GeneGroup
            "HLA-A",
            "HLA-B",
            "HLA-C",
            "HLA-E",
            "HLA-F",
            "HLA-G",
            "HLA-DRB1",
            "HLA-DRB3",
            "HLA-DRB5",
            "HLA-DRP1",
            "HLA-DRQ1",
            "HLA-DRA",
            "HLA-DQA1",
            "HLA-DPA1",
            "TLR1",
            "TLR6",
            "TLR10",
            "OAS1",
            "ACE",
            "ADRA1A",
            "ADRA1B",
            "ADRA1D",
            "ADRA2A",
            "ADRA2B",
            "ADRA2C",
            "ADRB1",
            "ADRB2",
            "ADRB3",
            "ANK2",
            "ATP1A1",
            "ATP1A2",
            "BRAF",
            "CACNA1C",
            "CACNA1D",
            "CACNA1G",
            "CACNA1H",
            "CASQ2",
            "CFTR",
            "CRHR1",
            "DRD1",
            "DRD2",
            "DRD3",
            "DRD4",
            "DRD5",
            "DSP",
            "EGFR",
            "ERBB2",
            "ERBB3",
            "ERBB4",
            "ESR1",
            "FDFT1",
            "FDPS",
            "FGFR1",
            "FKBP1A",
            "FLT3",
            "GABRA1",
            "GABRG2",
            "GJA1",
            "GJA5",
            "GJA7",
            "GRK4",
            "HCN2",
            "HCN4",
            "HMGCR",
            "HMGCS1",
            "HSD11B2",
            "HTR1A",
            "HTR1B",
            "HTR1D",
            "HTR1E",
            "HTR1F",
            "HTR2A",
            "HTR2B",
            "HTR2C",
            "HTR3A",
            "HTR3B",
            "HTR3C",
            "HTR3D",
            "HTR3E",
            "HTR4",
            "HTR5A",
            "HTR6",
            "HTR7",
            "JUP",
            "KCNA5",
            "KCND3",
            "KCNH2",
            "KCNJ11",
            "KCNJ2",
            "KCNJ3",
            "KCNJ4",
            "KCNJ5",
            "KCNJ8",
            "KCNK1",
            "KCNK3",
            "KCNQ1",
            "KIT",
            "LMNA",
            "NEDD4L",
            "NPR1",
            "NR1I2",
            "OPRM1",
            "PDGFR",
            "PEAR1",
            "PPIA",
            "PTGS1",
            "PTGS2",
            "RAF1",
            "RET",
            "RYR1",
            "RYR2",
            "SCN5A",
            "SCNN1A",
            "SCNN1B",
            "SCNN1D",
            "SCNN1G",
            "SERCA1",
            "SERCA2",
            "SGK1",
            "SLC6A2",
            "SLC6A3",
            "SLC6A4",
            "SLC8A2",
            "SLC8A3",
            "VDR",
            "VEGFR1",
            "VEGFR2",
            "VEGFR3",
            "VKORC1",
            "WNK1",
            "WNK4",
        ],
        2: [  # The key 2 corresponds to Pharmacokinetic GeneGroup
            "CYP2C19",
            "CYP2D6",
            "NAT2",
            "CYP1A1",
            "CYP1A2",
            "CYP2A6",
            "CYP2B6",
            "CYP2C8",
            "CYP2C9",
            "CYP2E1",
            "CYP2J2",
            "CYP3A4",
            "CYP3A5",
            "CYP4F2",
            "ABCB1",
            "ABCC2",
            "ABCG2",
            "ADH1B",
            "APOE",
            "BCHE",
            "DPYD",
            "EPHX1",
            "G6PD",
            "GSTM1",
            "GSTP1",
            "GSTT1",
            "GSTT2B",
            "NAT1",
            "NUDT15",
            "OPRM1",
            "SLC15A2",
            "SLC22A1",
            "SLC22A2",
            "SLC22A6",
            "SLCO1B1",
            "SLCO1B3",
            "SLCO2B1",
            "SULT1A1",
            "TPMT",
            "UGT1A1",
            "UGT1A3",
            "UGT1A4",
            "UGT1A6",
            "UGT1A8",
            "UGT1A9",
            "UGT2B15",
            "UGT2B17",
            "UGT2B7",
            "SLC2A4",
            "SLC2A9",
            "SLC6A2",
            "SLC6A3",
            "SLC6A4",
            "SLC12A1",
            "SLC12A3",
            "SLC22A3",
            "SLC22A12",
        ],
    }

    for gene_group_id, gene_list in dict_for_update.items():
        try:
            gene_group = GeneGroups.objects.get(id=gene_group_id)

            # Limpiar las relaciones existentes de forma eficiente
            gene_group.genes.clear()

            # Encontrar los genes que faltan y crearlos en una sola operación (bulk_create)
            existing_gene_names = Gene.objects.filter(name__in=gene_list).values_list(
                "name", flat=True
            )
            missing_gene_names = list(set(gene_list) - set(existing_gene_names))

            if missing_gene_names:
                Gene.objects.bulk_create(
                    [Gene(name=name) for name in missing_gene_names]
                )

                GeneStatus = apps.get_model("business_app", "GeneStatus")
                GeneStatusMiddle = apps.get_model("business_app", "GeneStatusMiddle")

                missing_genes = Gene.objects.filter(name__in=missing_gene_names)
                gene_status_list = GeneStatus.objects.all()
                gene_status_middle_list = []
                for gen in missing_genes:
                    gene_status_middle_list.extend(
                        [
                            GeneStatusMiddle(
                                gene=gen,
                                gene_status=gene_status,
                            )
                            for gene_status in gene_status_list
                        ]
                    )
                GeneStatusMiddle.objects.bulk_create(gene_status_middle_list)

            # Obtener todos los objetos Gene necesarios en una sola consulta
            genes_to_add = Gene.objects.filter(name__in=gene_list)

            # Añadir todos los genes al grupo en una sola operación
            gene_group.genes.add(*genes_to_add)

        except GeneGroups.DoesNotExist:
            print(
                f"Error: GeneGroups con id={gene_group_id} no fue encontrado. Omitiendo este grupo."
            )
        except Exception as e:
            print(
                f"Ocurrió un error inesperado al procesar el grupo {gene_group_id}: {e}"
            )
            raise  # Vuelve a lanzar la excepción para detener la migración

    # Esta línea elimina genes huérfanos, lo cual es una buena práctica
    Gene.objects.filter(groups__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0082_genestatusmiddle_created_timestamp_and_more"),
    ]

    operations = [
        migrations.RunPython(update_gene_list, migrations.RunPython.noop),
    ]
