# Generated by Django 5.0.6 on 2026-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0083_update_gene_list_for_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gene",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
