# Generated by Django 5.0.6 on 2026-02-17 03:59

import django.db.models.deletion
from django.db import migrations, models


def create_subcountries(apps, schema_editor):
    """Create SubCountry objects for each Country.
    For United States (code='US'), create 3 subregions with identificative suffixes.
    For other countries, create one SubCountry with the same name."""
    Country = apps.get_model("users_app", "Country")
    SubCountry = apps.get_model("business_app", "SubCountry")

    subcountries_to_create = []

    for country in Country.objects.all():
        if country.code == "US":
            subcountries_to_create.append(
                SubCountry(name=f"{country.name} - East", country=country),
            )
            subcountries_to_create.append(
                SubCountry(name=f"{country.name} - West", country=country),
            )
            subcountries_to_create.append(
                SubCountry(
                    name=f"{country.name} - Central and Mountains", country=country
                ),
            )
        else:
            # Create one SubCountry with the same name as the country
            subcountries_to_create.append(
                SubCountry(name=country.name, country=country)
            )

    # Create all SubCountry objects in a single batch operation
    SubCountry.objects.bulk_create(subcountries_to_create)


def reverse_subcountries(apps, schema_editor):
    """Reverse operation: delete all SubCountry objects."""
    SubCountry = apps.get_model("business_app", "SubCountry")
    SubCountry.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0084_alter_gene_name"),
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcountries",
                        to="users_app.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubCountry",
                "verbose_name_plural": "SubCountries",
            },
        ),
        migrations.RunPython(create_subcountries, reverse_subcountries),
    ]
