# Generated by Django 5.0.6 on 2026-02-17 03:59

import django.db.models.deletion
from django.db import migrations, models
from apps.business_app.tasks import create_subcountries_task


def create_subcountries(apps, schema_editor):
    """Create SubCountry objects for each Country.
    For United States (code='US'), create 3 subregions with identificative suffixes.
    For other countries, create one SubCountry with the same name."""
    create_subcountries_task().delay()


def reverse_subcountries(apps, schema_editor):
    """Reverse operation: delete all SubCountry objects."""
    SubCountry = apps.get_model("business_app", "SubCountry")
    SubCountry.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0084_alter_gene_name"),
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcountries",
                        to="users_app.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubCountry",
                "verbose_name_plural": "SubCountries",
            },
        ),
        migrations.RunPython(create_subcountries, reverse_subcountries),
    ]
