# Generated by Django 5.0.6 on 2026-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0085_subcountry"),
        ("users_app", "0015_country_latitude_country_longitude"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subcountry",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_region_in_country"
            ),
        ),
    ]
