# Generated by Django 5.0.6 on 2026-04-11 19:39

from django.db import migrations, models


def current_processed_as_true(apps, schema_editor):
    """"""
    UploadedFiles = apps.get_model("business_app", "UploadedFiles")
    UploadedFiles.objects.all().update(processed=True)


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0086_subcountry_unique_region_in_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(current_processed_as_true, migrations.RunPython.noop),
    ]
