# Generated by Django 5.0.6 on 2026-04-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0087_uploadedfiles_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="predecessors",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="allelenode",
            name="sucessors",
            field=models.JSONField(default=list),
        ),
    ]
