# Generated by Django 5.0.6 on 2026-05-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0088_allelenode_predecessors_allelenode_sucessors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allelenode",
            name="allele",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Allele"
            ),
        ),
    ]
