# Generated by Django 5.0.6 on 2026-05-31 02:58

import django.db.models.deletion
from django.db import migrations, models


def create_study_types(apps, schema_editor):
    StudyType = apps.get_model("business_app", "StudyType")
    StudyType.objects.create(name="Genetic Allele", sheet_name="For3DAllele")
    StudyType.objects.create(name="Location+Est", sheet_name="For3DProt_L+Est")
    StudyType.objects.create(name="Location-Est", sheet_name="For3DProt_L-Est")
    StudyType.objects.create(name="Ancesters+Est", sheet_name="For3DProt_A+Est")
    StudyType.objects.create(name="Ancesters-Est", sheet_name="For3DProt_A-Est")


def reverse_study_types(apps, schema_editor):
    StudyType = apps.get_model("business_app", "StudyType")
    StudyType.objects.filter(
        name__in=[
            "Genetic Allele",
            "Location+Est",
            "Location-Est",
            "Ancesters+Est",
            "Ancesters-Est",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0088_allelenode_predecessors_allelenode_sucessors"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "sheet_name",
                    models.CharField(max_length=100, verbose_name="Sheet Name"),
                ),
            ],
            options={
                "verbose_name": "Study Type",
                "verbose_name_plural": "Study Types",
            },
        ),
        migrations.RunPython(create_study_types, reverse_study_types),
        migrations.RenameField(
            model_name="allelenode",
            old_name="custom_element_name",
            new_name="allele",
        ),
        migrations.RemoveField(
            model_name="allelenode",
            name="uploaded_file",
        ),
        migrations.RemoveField(
            model_name="pdbfiles",
            name="original_file",
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "successfull_load",
                    models.BooleanField(default=False, verbose_name="Successful Load"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "extra_info",
                    models.TextField(blank=True, null=True, verbose_name="Extra Info"),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="business_app.uploadedfiles",
                    ),
                ),
                (
                    "study_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="studies",
                        to="business_app.studytype",
                        verbose_name="Study Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study",
                "verbose_name_plural": "Studies",
            },
        ),
        migrations.CreateModel(
            name="ProteinNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Number")),
                (
                    "unique_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Unique Number"
                    ),
                ),
                ("element", models.CharField(max_length=3, verbose_name="Element")),
                (
                    "allele",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Allele"
                    ),
                ),
                ("rs", models.TextField(verbose_name="RS")),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Region"
                    ),
                ),
                ("predecessors", models.JSONField(default=list)),
                ("sucessors", models.JSONField(default=list)),
                (
                    "timeline_appearence",
                    models.IntegerField(
                        null=True, verbose_name="Appearance on the timeline"
                    ),
                ),
                (
                    "age_1",
                    models.IntegerField(
                        help_text="First value in the appereance range",
                        null=True,
                        verbose_name="Appearance on the timeline",
                    ),
                ),
                (
                    "age_2",
                    models.IntegerField(
                        help_text="Last value in the appereance range",
                        null=True,
                        verbose_name="Disappearance on the timeline",
                    ),
                ),
                ("loss", models.TextField(null=True, verbose_name="RS lost")),
                (
                    "increment",
                    models.TextField(null=True, verbose_name="RS incremented"),
                ),
                (
                    "sphere_radius",
                    models.FloatField(null=True, verbose_name="Sphere Radius"),
                ),
                (
                    "stick_radius",
                    models.FloatField(null=True, verbose_name="Stick Radius"),
                ),
                (
                    "frec_afr_amr",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Frequency African American/Afro-Caribbean",
                    ),
                ),
                (
                    "frec_amr",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency American"
                    ),
                ),
                (
                    "frec_csa",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Frequency Central/South-Asian",
                    ),
                ),
                (
                    "frec_eas",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency East Asian"
                    ),
                ),
                (
                    "frec_eur",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency European"
                    ),
                ),
                (
                    "frec_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency Latino"
                    ),
                ),
                (
                    "frec_nea",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency Near Eastern"
                    ),
                ),
                (
                    "frec_oce",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency Oceanian"
                    ),
                ),
                (
                    "frec_ssa",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Frequency Sub-Saharan African",
                    ),
                ),
                (
                    "frec_afr_eas",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency East-African"
                    ),
                ),
                (
                    "frec_afr_swe",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Frequency South-West-African",
                    ),
                ),
                (
                    "frec_afr_nor",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency North-African"
                    ),
                ),
                (
                    "frec_ca",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency Central-Asian"
                    ),
                ),
                (
                    "frec_sa",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frequency South-Asian"
                    ),
                ),
                (
                    "is_final_for_allele",
                    models.BooleanField(
                        default=False, verbose_name="Is Final For Allele"
                    ),
                ),
                (
                    "children",
                    models.ManyToManyField(blank=True, to="business_app.proteinnode"),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business_app.study",
                        verbose_name="Study ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protein Node",
                "verbose_name_plural": "Protein Nodes",
            },
        ),
        migrations.AddField(
            model_name="allelenode",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_allele_nodes",
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
        migrations.AddField(
            model_name="pdbfiles",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdb_files",
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
    ]
