# Generated by Django 5.0.6 on 2026-06-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_app",
            "0089_studytype_remove_allelenode_custom_element_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="allelenode",
            name="allele",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Allele"
            ),
        ),
        migrations.AlterField(
            model_name="proteinnode",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_protein_nodes",
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
    ]
