# Generated by Django 5.0.6 on 2026-05-18 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0089_proteinnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteinnode",
            name="children",
            field=models.ManyToManyField(blank=True, to="business_app.proteinnode"),
        ),
        migrations.AlterField(
            model_name="allelenode",
            name="allele",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Allele"
            ),
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[
                            ("G", "Genetic Allele"),
                            ("L", "Location"),
                            ("A", "Ancestors"),
                        ],
                        default="G",
                        max_length=1,
                        verbose_name="Study Type",
                    ),
                ),
                (
                    "successfull_load",
                    models.BooleanField(default=False, verbose_name="Successful Load"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "extra_info",
                    models.TextField(blank=True, null=True, verbose_name="Extra Info"),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="business_app.uploadedfiles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study",
                "verbose_name_plural": "Studies",
            },
        ),
    ]
