# Generated by Django 5.0.6 on 2026-06-09 16:26

from django.db import migrations, models


def update_study_types_classifications(apps, schema_editor):
    StudyType = apps.get_model("business_app", "StudyType")
    StudyType.objects.exclude(name="Genetic Allele", sheet_name="For3DAllele").update(
        classification="P"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0090_alter_allelenode_allele_alter_proteinnode_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="studytype",
            name="classification",
            field=models.CharField(
                choices=[("A", "Allele"), ("P", "Protein")],
                default="A",
                max_length=1,
                verbose_name="Classification",
            ),
        ),
        migrations.RunPython(update_study_types_classifications),
    ]
