# Generated by Django 5.0.6 on 2026-05-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0090_proteinnode_children_alter_allelenode_allele_study"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allelenode",
            name="uploaded_file",
        ),
        migrations.RemoveField(
            model_name="proteinnode",
            name="uploaded_file",
        ),
        migrations.AddField(
            model_name="allelenode",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
        migrations.AddField(
            model_name="proteinnode",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
    ]
