# Generated by Django 5.0.6 on 2026-07-07 17:20

from django.db import migrations


def update_study_types(apps, schema_editor):
    StudyType = apps.get_model("business_app", "StudyType")
    StudyType.objects.filter(sheet_name="For3DAllele").update(name="Genomic Allele")
    StudyType.objects.filter(sheet_name="For3DProt_A+Est").update(name="Ancestral+Est")
    StudyType.objects.filter(sheet_name="For3DProt_A-Est").update(name="Ancestral-Est")


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0091_studytype_classification"),
    ]

    operations = [
        migrations.RunPython(update_study_types, migrations.RunPython.noop),
    ]
