# Generated by Django 5.0.6 on 2026-05-19 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0091_remove_redundant_uploaded_file_fks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdbfiles",
            name="original_file",
        ),
        migrations.AddField(
            model_name="pdbfiles",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
    ]
