# Generated by Django 5.0.6 on 2026-05-27 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0092_remove_pdbfiles_original_file_pdbfiles_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdbfiles",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdb_files",
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
    ]
