# Generated by Django 5.0.6 on 2026-07-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0092_update_studytype_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelenode",
            name="order",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Order"),
        ),
        migrations.AddField(
            model_name="proteinnode",
            name="order",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Order"),
        ),
    ]
