# Generated by Django 5.0.6 on 2026-05-29 17:17

import django.db.models.deletion
from django.db import migrations, models


def create_study_types(apps, schema_editor):
    StudyType = apps.get_model("business_app", "StudyType")
    StudyType.objects.create(name="Genetic Allele", sheet_name="For3DAllele")
    StudyType.objects.create(name="Location+Est", sheet_name="For3DProt_L+Est")
    StudyType.objects.create(name="Location-Est", sheet_name="For3DProt_L-Est")
    StudyType.objects.create(name="Ancesters+Est", sheet_name="For3DProt_A+Est")
    StudyType.objects.create(name="Ancesters-Est", sheet_name="For3DProt_A-Est")


def reverse_study_types(apps, schema_editor):
    StudyType = apps.get_model("business_app", "StudyType")
    StudyType.objects.filter(
        name__in=[
            "Genetic Allele",
            "Location+Est",
            "Location-Est",
            "Ancesters+Est",
            "Ancesters-Est",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0093_alter_pdbfiles_study"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "sheet_name",
                    models.CharField(max_length=100, verbose_name="Sheet Name"),
                ),
            ],
            options={
                "verbose_name": "Study Type",
                "verbose_name_plural": "Study Types",
            },
        ),
        migrations.RunPython(create_study_types, reverse_study_types),
        migrations.AlterField(
            model_name="allelenode",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_allele_nodes",
                to="business_app.study",
                verbose_name="Study ID",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="study_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="studies",
                to="business_app.studytype",
                verbose_name="Study Type",
            ),
        ),
    ]
