[pytest]
DJANGO_SETTINGS_MODULE = project_site.settings
python_files = tests.py test_*.py *_tests.py
filterwarnings =
	ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning:coreapi\.codecs\.download
