# Generated by Django 5.0.6 on 2026-01-03 16:43

import apps.allele_mapping.models.allele_mapping_files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("business_app", "0083_update_gene_list_for_groups"),
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlleleRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "population",
                    models.CharField(max_length=100, verbose_name="population"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="location"
                    ),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "lon",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
            ],
            options={
                "verbose_name": "Allele Region",
                "verbose_name_plural": "Allele Regions",
            },
        ),
        migrations.CreateModel(
            name="AlleleMappingFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.allele_mapping.models.allele_mapping_files.user_directory_path,
                        validators=[
                            apps.allele_mapping.models.allele_mapping_files.FileExtensionValidator()
                        ],
                        verbose_name="Original File",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "system_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele_mapping_files",
                        to="users_app.systemuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele mapping uploaded File",
                "verbose_name_plural": "Allele mapping uploaded Files",
            },
        ),
        migrations.CreateModel(
            name="AlleleRegionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent_of_individuals",
                    models.FloatField(
                        blank=True, null=True, verbose_name="percent of individuals"
                    ),
                ),
                (
                    "allele_frequency",
                    models.FloatField(
                        blank=True, null=True, verbose_name="allele frequency"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="sample size"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alleles",
                        to="allele_mapping.alleleregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele region info",
                "verbose_name_plural": "Alleles region info",
            },
        ),
        migrations.CreateModel(
            name="AlleleToMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alleles",
                        to="allele_mapping.allelemappingfiles",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele_mapping_files",
                        to="business_app.gene",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        through="allele_mapping.AlleleRegionInfo",
                        to="allele_mapping.alleleregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele to map",
                "verbose_name_plural": "Alleles to map",
            },
        ),
        migrations.AddField(
            model_name="alleleregioninfo",
            name="allele",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allele_regions",
                to="allele_mapping.alleletomap",
            ),
        ),
    ]
