# Generated by Django 5.0.6 on 2026-01-03 03:55

import apps.allele_mapping.models.allele_mapping_files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlleleMappingFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.allele_mapping.models.allele_mapping_files.user_directory_path,
                        validators=[
                            apps.allele_mapping.models.allele_mapping_files.FileExtensionValidator()
                        ],
                        verbose_name="Original File",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "system_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele_mapping_files",
                        to="users_app.systemuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele mapping uploaded File",
                "verbose_name_plural": "Allele mapping uploaded Files",
            },
        ),
    ]
