# Generated by Django 5.0.6 on 2026-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_mapping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alleleregioninfo",
            name="allele_frequency",
            field=models.FloatField(
                blank=True, db_index=True, null=True, verbose_name="allele frequency"
            ),
        ),
        migrations.AlterField(
            model_name="alleleregioninfo",
            name="percent_of_individuals",
            field=models.FloatField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="percent of individuals",
            ),
        ),
        migrations.AlterField(
            model_name="alleleregioninfo",
            name="sample_size",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="sample size"
            ),
        ),
        migrations.AlterField(
            model_name="alleletomap",
            name="name",
            field=models.CharField(db_index=True, max_length=50, verbose_name="name"),
        ),
    ]
