# Generated by Django 5.0.6 on 2026-01-03 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_mapping", "0001_initial"),
        ("business_app", "0083_update_gene_list_for_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlleleToMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alleles",
                        to="allele_mapping.allelemappingfiles",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele_mapping_files",
                        to="business_app.gene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele to map",
                "verbose_name_plural": "Alleles to map",
            },
        ),
        migrations.CreateModel(
            name="AlleleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "population",
                    models.CharField(max_length=100, verbose_name="population"),
                ),
                (
                    "percent_of_indivicuals",
                    models.FloatField(
                        blank=True, null=True, verbose_name="percent of individuals"
                    ),
                ),
                (
                    "allele_frequency",
                    models.FloatField(
                        blank=True, null=True, verbose_name="allele frequency"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="sample size"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="location"
                    ),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "lon",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele_info",
                        to="allele_mapping.alleletomap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele info",
                "verbose_name_plural": "Alleles info",
            },
        ),
    ]
