# Generated by Django 5.0.6 on 2026-01-03 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("allele_mapping", "0002_alleletomap_alleleinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alleleinfo",
            old_name="percent_of_indivicuals",
            new_name="percent_of_individuals",
        ),
    ]
