# Generated by Django 5.0.6 on 2026-02-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_mapping", "0002_alter_alleleregioninfo_allele_frequency_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alleleregioninfo",
            index=models.Index(
                fields=["allele_frequency", "sample_size"], name="idx_freq_sample"
            ),
        ),
        migrations.AddIndex(
            model_name="alleleregioninfo",
            index=models.Index(
                fields=["region", "allele_frequency"], name="idx_region_freq"
            ),
        ),
        migrations.AddIndex(
            model_name="alleleregioninfo",
            index=models.Index(
                fields=["allele", "allele_frequency", "sample_size"],
                name="idx_allele_freq_sample",
            ),
        ),
    ]
