# Generated by Django 5.0.6 on 2026-02-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_mapping", "0003_add_composite_indexes"),
        ("business_app", "0085_subcountry"),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleregion",
            name="sub_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allele_countries",
                to="business_app.subcountry",
            ),
        ),
    ]
