# Generated by Django 5.0.6 on 2026-03-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_mapping", "0004_alleleregion_sub_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alleleregion",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="alleleregion",
            name="location",
        ),
        migrations.RemoveField(
            model_name="alleleregion",
            name="lon",
        ),
        migrations.CreateModel(
            name="AlleleRegionCoord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="location"
                    ),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "lon",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
                (
                    "allele_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinates",
                        to="allele_mapping.alleleregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele Region Coordinate",
                "verbose_name_plural": "Allele Region Coordinates",
            },
        ),
    ]
