# Generated by Django 5.0.6 on 2026-03-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "allele_mapping",
            "0005_remove_alleleregion_lat_remove_alleleregion_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="alleleregion",
            name="sub_country_incoming_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="sub country incoming name",
            ),
        ),
        migrations.AddField(
            model_name="alleleregioninfo",
            name="kind_of_info",
            field=models.CharField(
                choices=[("P", "primary"), ("S", "secondary")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="alleleregioncoord",
            constraint=models.UniqueConstraint(
                fields=("lat", "lon"), name="unique_lat_lon"
            ),
        ),
    ]
