# Generated by Django 4.1.7 on 2023-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deletion_timestamp",
                    models.DateTimeField(verbose_name="Deletion timestamp"),
                ),
                (
                    "deletion_cause",
                    models.TextField(
                        blank=True, null=True, verbose_name="deletion cause"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historical Vault",
                "verbose_name_plural": "Historical Vaults",
            },
        ),
    ]
