# Generated by Django 4.2.1 on 2023-07-12 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0002_remove_systemuser_historical_vault_and_more"),
        ("common", "0002_historicalvault_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalVault",
        ),
    ]
