# Generated by Django 5.0.6 on 2025-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlleleSNPInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parents_info",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Parents Info"
                    ),
                ),
                (
                    "allele",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Allele"
                    ),
                ),
                (
                    "loss_ancesters_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP lost (Ancesters)"
                    ),
                ),
                (
                    "increment_ancesters_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP increment (Ancesters)"
                    ),
                ),
                (
                    "loss_location_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP lost (Location)"
                    ),
                ),
                (
                    "increment_location_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP increment (Location)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele SNP Information",
                "verbose_name_plural": "Alleles SNP Information",
            },
        ),
    ]
