# Generated by Django 5.0.6 on 2025-07-20 05:26

import apps.allele_formation.models.uploaded_snp_files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedSNPFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(max_length=150, verbose_name="custom name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "snp_file",
                    models.FileField(
                        upload_to=apps.allele_formation.models.uploaded_snp_files.user_directory_path,
                        validators=[
                            apps.allele_formation.models.uploaded_snp_files.FileExtensionValidator()
                        ],
                        verbose_name="Original File",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "system_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snp_files",
                        to="users_app.systemuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNP File",
                "verbose_name_plural": "SNP Files",
            },
        ),
        migrations.CreateModel(
            name="AlleleSNPInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parents_info",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Parents Info"
                    ),
                ),
                (
                    "allele",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Allele"
                    ),
                ),
                (
                    "loss_ancesters_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP lost (Ancesters)"
                    ),
                ),
                (
                    "increment_ancesters_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP increment (Ancesters)"
                    ),
                ),
                (
                    "loss_location_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP lost (Location)"
                    ),
                ),
                (
                    "increment_location_snp",
                    models.TextField(
                        blank=True, null=True, verbose_name="SNP increment (Location)"
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allele_snp_info",
                        to="allele_formation.uploadedsnpfiles",
                        verbose_name="Uploaded SNP File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allele SNP Information",
                "verbose_name_plural": "Alleles SNP Information",
            },
        ),
    ]
