# Generated by Django 5.0.6 on 2025-07-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_formation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedsnpfiles",
            name="predefined",
            field=models.BooleanField(default=False, verbose_name="predefined"),
        ),
    ]
