# Generated by Django 5.0.6 on 2025-07-20 06:34

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_formation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SNPAlleleLocationFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="Order")),
                ("formation", models.CharField(verbose_name="Formation")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#808080",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Color",
                    ),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allele_formation.allelesnpinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNP Allele Location Formation",
                "verbose_name_plural": "SNP Alleles Location Formation",
            },
        ),
        migrations.CreateModel(
            name="SNPAlleleParentsFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="Order")),
                ("formation", models.CharField(verbose_name="Formation")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#808080",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Color",
                    ),
                ),
                (
                    "allele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allele_formation.allelesnpinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNP Allele Parent Formation",
                "verbose_name_plural": "SNP Alleles Parent Formation",
            },
        ),
    ]
