# Generated by Django 5.0.6 on 2025-07-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "allele_formation",
            "0002_snpallelelocationformation_snpalleleparentsformation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="allelesnpinfo",
            name="allele",
            field=models.CharField(max_length=100, verbose_name="Allele"),
        ),
        migrations.AddConstraint(
            model_name="allelesnpinfo",
            constraint=models.UniqueConstraint(
                fields=("allele", "uploaded_file"), name="unique_allele_uploaded_file"
            ),
        ),
    ]
