# Generated by Django 5.0.6 on 2025-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_formation", "0002_uploadedsnpfiles_predefined"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelesnpinfo",
            name="transition",
            field=models.TextField(blank=True, null=True, verbose_name="Transition"),
        ),
    ]
