# Generated by Django 5.0.6 on 2025-08-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allele_formation", "0003_allelesnpinfo_transition"),
        ("business_app", "0070_uploadedfiles_predefined"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedsnpfiles",
            name="gene",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_formation_files",
                to="business_app.gene",
            ),
        ),
    ]
