# Generated by Django 4.2.1 on 2023-07-04 05:58

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_superuser(apps, schema_editor):
    SystemUser = apps.get_model("users_app", "SystemUser")
    SystemUser.objects.create_user(
        username="admin",
        password="1qazxsw2",
        first_name="Admin",
        last_name="Generic",
        email="admin@commonuser.com",
        identification_number="000000000000",
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )
    print()
    print(bcolors.OKCYAN + "SuperAdmin creado exitosamente")
    print(bcolors.OKBLUE + "Usuario:" + bcolors.OKGREEN + "admin")
    print(bcolors.OKBLUE + "Password:" + bcolors.OKGREEN + "1qazxsw2")


class bcolors:
    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKCYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0002_historicalvault_author"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        help_text="CI or Passport",
                        max_length=20,
                        unique=True,
                        verbose_name="identification number",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="photo"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female"), ("O", "other")],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only numeric characters allowed",
                                regex="^\\+?\\d+$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "historical_vault",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.historicalvault",
                        verbose_name="NOT USED",
                    ),
                ),
            ],
            options={
                "verbose_name": "System user",
                "verbose_name_plural": "System users",
                "abstract": False,
            },
            bases=("auth.user", models.Model),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]
