# Generated by Django 4.2.1 on 2023-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial_creating_users_structure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemuser",
            name="historical_vault",
        ),
        migrations.AddField(
            model_name="systemuser",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
