# Generated by Django 4.2.1 on 2023-07-12 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0002_remove_systemuser_historical_vault_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="systemuser",
            managers=[],
        ),
    ]
