# Generated by Django 4.2.1 on 2023-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0003_alter_systemuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="internal_status",
            field=models.CharField(
                choices=[("R", "registered"), ("C", "confirmed"), ("P", "has paid")],
                default="R",
                max_length=1,
                verbose_name="internal status",
            ),
        ),
    ]
