# Generated by Django 4.2.1 on 2023-07-21 14:59

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0004_systemuser_internal_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="systemuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="created_timestamp",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="updated_timestamp",
        ),
    ]
