# Generated by Django 4.2.1 on 2023-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0005_alter_systemuser_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Country name")),
                ("code", models.CharField(max_length=2, verbose_name="Country code")),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "abstract": False,
            },
        ),
    ]
