# Generated by Django 4.2.1 on 2023-07-21 17:10

import json

from django.db import migrations
from termcolor import colored


def populate_countries(apps, schema_editor):
    Country = apps.get_model("users_app", "Country")

    with open("apps/users_app/fixtures/country_data.json", "r") as f:
        data = json.load(f)
    counter = 0
    for item in data:
        counter += 1
        Country.objects.create(code=item["Code"], name=item["Name"])
    print()
    print(
        colored(
            f"Successfully added {counter} countries to the system",
            "green",
            attrs=["reverse", "blink"],
        )
    )


def delete_countries(apps, schema_editor):
    Country = apps.get_model("users_app", "Country")
    Country.objects.all().delete()
    print()
    print(
        colored(
            "Successfully removed all the countries on the system",
            "red",
            attrs=["reverse", "blink"],
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0007_systemuser_country"),
    ]

    operations = [
        migrations.RunPython(populate_countries, delete_countries),
    ]
