# Generated by Django 4.2.1 on 2023-07-23 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0008_fill_country_list"),
    ]

    operations = []
