# Generated by Django 4.2.1 on 2023-08-03 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0009_systemuser_participation_modality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only numeric characters allowed", regex="^\\+?\\d+$"
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
