# Generated by Django 5.0.6 on 2024-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_systemuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="internal_status",
            field=models.CharField(
                choices=[("R", "registered"), ("C", "confirmed"), ("P", "premium")],
                default="R",
                max_length=1,
                verbose_name="internal status",
            ),
        ),
    ]
