# Generated by Django 5.0.6 on 2024-07-23 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_systemuser_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemuser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="identification_number",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="internal_status",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="photo",
        ),
    ]
