# Generated by Django 4.2.7 on 2024-07-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0029_uploadedfiles_created_at_workingcopyoforiginalfile"),
        ("users_app", "0010_alter_systemuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="working_copy_of_original_file",
            field=models.ManyToManyField(
                through="business_app.WorkingCopyOfOriginalFile",
                to="business_app.uploadedfiles",
            ),
        ),
    ]
