# Generated by Django 5.0.6 on 2024-07-23 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0011_systemuser_working_copy_of_original_file"),
        ("users_app", "0012_systemuser_internal_status"),
    ]

    operations = []
