# Generated by Django 5.0.6 on 2024-09-05 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0011_alter_systemuser_internal_status"),
        ("users_app", "0013_merge_20240723_1641"),
    ]

    operations = []
