# Generated by Django 5.0.6 on 2026-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="latitude",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="longitude",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Longitude"
            ),
        ),
    ]
