# Generated by Django 5.0.6 on 2026-01-02 17:00

import apps.genes_to_excel.models.genes_to_excel_files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("business_app", "0083_update_gene_list_for_groups"),
        ("users_app", "0014_merge_20240905_0947"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenesToExcelFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(max_length=150, verbose_name="custom name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.genes_to_excel.models.genes_to_excel_files.user_directory_path,
                        validators=[
                            apps.genes_to_excel.models.genes_to_excel_files.FileExtensionValidator()
                        ],
                        verbose_name="Original File",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genes_to_excel_files",
                        to="business_app.gene",
                    ),
                ),
                (
                    "system_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genes_to_excel_files",
                        to="users_app.systemuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genes to excel uploaded File",
                "verbose_name_plural": "Genes to excel uploaded Files",
            },
        ),
    ]
