# Generated by Django 5.0.6 on 2026-01-05 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0083_update_gene_list_for_groups"),
        ("genes_to_excel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracteristicaGen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo_origen",
                    models.CharField(
                        help_text="Nombre del archivo Excel de origen", max_length=255
                    ),
                ),
                ("gene", models.CharField(blank=True, max_length=100)),
                ("cord", models.CharField(blank=True, max_length=50)),
                ("valor", models.CharField(blank=True, max_length=10)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("protein", models.CharField(blank=True, max_length=100)),
                ("alleleasoc", models.TextField(blank=True)),
                ("species", models.CharField(blank=True, max_length=100)),
                ("variant", models.CharField(blank=True, max_length=100)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "gen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristicas",
                        to="business_app.gene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Característica del Gen",
                "verbose_name_plural": "Características de los Genes",
                "db_table": "caracteristicas_gen",
                "indexes": [
                    models.Index(
                        fields=["gene", "cord"], name="caracterist_gene_30bf38_idx"
                    ),
                    models.Index(fields=["gene"], name="caracterist_gene_12c584_idx"),
                    models.Index(
                        fields=["species"], name="caracterist_species_d9568c_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="caracteristicagen",
            constraint=models.UniqueConstraint(
                fields=("gen", "cord"), name="unique_gen_cord_combination"
            ),
        ),
    ]
