# Generated by Django 5.0.6 on 2026-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0002_caracteristicagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristicagen",
            name="order",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
