# Generated by Django 5.0.6 on 2026-03-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0003_caracteristicagen_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caracteristicagen",
            old_name="order",
            new_name="order_one",
        ),
        migrations.AddField(
            model_name="caracteristicagen",
            name="order_three",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="caracteristicagen",
            name="order_two",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
