# Generated by Django 5.0.6 on 2026-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0004_rename_order_caracteristicagen_order_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristicagen",
            name="alleleasoc",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
