# Generated by Django 5.0.6 on 2026-06-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0088_allelenode_predecessors_allelenode_sucessors"),
        ("genes_to_excel", "0005_alter_caracteristicagen_alleleasoc"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="caracteristicagen",
            index=models.Index(
                fields=["archivo_origen"], name="caracterist_archivo_a38446_idx"
            ),
        ),
    ]
