# Generated by Django 5.0.6 on 2026-06-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0006_caracteristicagen_caracterist_archivo_a38446_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristicagen",
            name="link",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
