# Generated by Django 5.0.6 on 2026-06-20 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0007_caracteristicagen_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caracteristicagen",
            old_name="link",
            new_name="ncbi_link",
        ),
    ]
