# Generated by Django 5.0.6 on 2026-07-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0008_rename_link_caracteristicagen_ncbi_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristicagen",
            name="valor",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
