# Generated by Django 5.0.6 on 2026-07-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0009_alter_caracteristicagen_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristicagen",
            name="alleleasoc",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caracteristicagen",
            name="ncbi_link",
            field=models.TextField(blank=True),
        ),
    ]
