# Generated by Django 5.0.6 on 2026-07-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genes_to_excel", "0010_alter_caracteristicagen_alleleasoc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristicagen",
            name="uploaded_excel_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="genes_to_excel.genestoexcelfiles",
            ),
        ),
    ]
